table V_Fact_FB_ToplineActuals_Summary
	lineageTag: 0ed7f2e9-b2e1-4f5d-8966-4cdfe99463f4

	column SalesGroupID
		dataType: string
		lineageTag: a2afd1bc-b6d1-4f44-9dc7-0b809cb98c6f
		summarizeBy: none
		sourceColumn: SalesGroupID

		annotation SummarizationSetBy = Automatic

	column SalesCases
		dataType: double
		lineageTag: ef624636-d456-4021-9431-728870aae162
		summarizeBy: sum
		sourceColumn: SalesCases

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueDeadNet
		dataType: double
		lineageTag: 7005c235-53bb-4f92-888b-3a4ae06a14ec
		summarizeBy: sum
		sourceColumn: RevenueDeadNet

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RC_Topline_Actuals = COUNTROWS(V_Fact_FB_ToplineActuals_Summary)
		formatString: 0
		lineageTag: f1af32f2-cf9d-49c7-b877-b66291157fd9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: 3c30231b-ca78-4e12-b134-643a1986e601
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NationalChainName
		dataType: string
		lineageTag: 1627f0ef-8f07-4d9a-b33b-bdf062bf6019
		summarizeBy: none
		sourceColumn: NationalChainName

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: double
		lineageTag: 2cb9c125-c129-414f-afe7-2c58cd3a716f
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition V_Fact_FB_ToplineActuals_Summary = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(#"Snowflake Server",#"Snowflake Warehouse",[Implementation="2.0"]),
				    SOLUTIONS_DEV_Database = Source{[Name=Snowflake_DataBase,Kind="Database"]}[Data],
				    DSD_Schema = SOLUTIONS_DEV_Database{[Name=Snowflake_Schema,Kind="Schema"]}[Data],
				    Fact = DSD_Schema{[Name="V_Fact_FB_ToplineActuals_Summary",Kind="View"]}[Data],
					Filtered = Table.SelectRows(Fact, each [Period] >= Range_Start and [Period] <= Range_End)
				in
				    Filtered

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

