table V_Fact_FB_Ops_Deliveryorder
	lineageTag: 0aed85cb-d06a-4e4e-b175-b02903d1fc4b

	column TerritoryName
		dataType: string
		lineageTag: 5efe5556-8756-439a-a224-0e0aae4dcd4d
		summarizeBy: none
		sourceColumn: TerritoryName

		annotation SummarizationSetBy = Automatic

	column SalesOfficeName
		dataType: string
		lineageTag: 654e8e18-7f8a-4397-95d5-025048dcc23d
		summarizeBy: none
		sourceColumn: SalesOfficeName

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: double
		lineageTag: a546dcb2-c6fb-4144-9eb9-c72e8536afd9
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: string
		lineageTag: ab5cbab1-a9e9-4f58-85df-84594523e9b2
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column InvoicedQty
		dataType: double
		lineageTag: 870fd7e4-4aa2-4b48-92ac-2453d7a172bd
		summarizeBy: sum
		sourceColumn: InvoicedQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AdjOrderQty
		dataType: double
		lineageTag: 1d0035db-f1e8-4d15-be6b-fc70eed297a7
		summarizeBy: sum
		sourceColumn: AdjOrderQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalOrder
		dataType: double
		lineageTag: 1ffac199-975d-43f6-a74f-79b1cce1bbbe
		summarizeBy: sum
		sourceColumn: TotalOrder

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month_new = V_Fact_FB_Ops_DeliveryOrder[Month]
		lineageTag: 7f0799e8-c169-41d4-a16b-9b6af2bd0a3e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MonthID
		dataType: string
		lineageTag: b34db1e2-7112-4f2e-8f1d-70ccea40c603
		summarizeBy: none
		sourceColumn: MonthID

		annotation SummarizationSetBy = Automatic

	partition V_Fact_FB_Ops_Deliveryorder = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(#"Snowflake Server",#"Snowflake Warehouse",[Implementation="2.0"]),
				    SOLUTIONS_DEV_Database = Source{[Name=Snowflake_DataBase,Kind="Database"]}[Data],
				    DSD_Schema = SOLUTIONS_DEV_Database{[Name=Snowflake_Schema,Kind="Schema"]}[Data],
				    Fact = DSD_Schema{[Name="V_Fact_FB_Ops_Deliveryorder",Kind="View"]}[Data],
					Rng1 = Date.ToText(Range_Start, "yyyyMM"),
					Rng2 = Date.ToText(Range_End, "yyyyMM"),
					AddMonthID = Table.AddColumn(Fact, "MonthID", each Text.Combine({Text.From([Year], "en-US"), [Month]}), type text),
					Filtered = Table.SelectRows(AddMonthID, each [MonthID] >= Rng1 and [MonthID] <= Rng2)
				in
				    Filtered

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

