table V_Fact_FB_Topline_Budget_All
	lineageTag: 9d532829-e432-471d-81cb-65df83d6bf8f

	column NationalChainName
		dataType: string
		lineageTag: 9595749e-38d0-4448-8126-f1f7c9383f46
		summarizeBy: none
		sourceColumn: NationalChainName

		annotation SummarizationSetBy = Automatic

	column SalesCasesBudget
		dataType: double
		formatString: 0.000
		lineageTag: 7c30e9d4-5787-44bf-a718-4c5d68940f4c
		summarizeBy: sum
		sourceColumn: SalesCasesBudget

		annotation SummarizationSetBy = Automatic

	column RevenueDeadNetBudget
		dataType: double
		formatString: 0.000
		lineageTag: 938afaba-f425-47c5-bd08-85faf4a63685
		summarizeBy: sum
		sourceColumn: RevenueDeadNetBudget

		annotation SummarizationSetBy = Automatic

	column SalesCasesFC
		dataType: double
		formatString: 0.000
		lineageTag: 017cd055-2f71-476e-8f1b-9d6093409b7e
		summarizeBy: sum
		sourceColumn: SalesCasesFC

		annotation SummarizationSetBy = Automatic

	column RevenueDeadNetFC
		dataType: double
		formatString: 0.000
		lineageTag: 9b72cd89-b825-44e4-ba6d-620ae9381bd2
		summarizeBy: sum
		sourceColumn: RevenueDeadNetFC

		annotation SummarizationSetBy = Automatic

	column RC_topline_budget = COUNTROWS(V_Fact_FB_Topline_Budget_All)
		formatString: 0
		lineageTag: f60f289a-6d5a-462e-92f5-d6c11b171fe5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column PeriodEnd
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: a8c9a0fe-3518-48aa-b97f-ebcdda82b577
		summarizeBy: none
		sourceColumn: PeriodEnd

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GPDeadNetBudget
		dataType: double
		lineageTag: 35bf3d04-4f28-4f81-8b7d-62c83a59f9d5
		summarizeBy: sum
		sourceColumn: GPDeadNetBudget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GPDeadNetFC
		dataType: double
		lineageTag: 6aa33681-8c61-4a81-b37e-a5d0e63cfb36
		summarizeBy: sum
		sourceColumn: GPDeadNetFC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesGroupID
		dataType: string
		lineageTag: 06520a6b-74c4-467f-a89d-d2298a6e6de3
		summarizeBy: none
		sourceColumn: SalesGroupID

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: double
		lineageTag: 9e08b33f-b0b7-409f-b5a5-9be0a3b9007c
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition V_Fact_FB_Topline_Budget_All = m
		mode: import
		queryGroup: Fact-Sales
		source =
				let
				    Source = Snowflake.Databases(#"Snowflake Server",#"Snowflake Warehouse",[Implementation="2.0"]),
				    SOLUTIONS_DEV_Database = Source{[Name=Snowflake_DataBase,Kind="Database"]}[Data],
				    DSD_Schema = SOLUTIONS_DEV_Database{[Name=Snowflake_Schema,Kind="Schema"]}[Data],
				    Fact = DSD_Schema{[Name="V_Fact_FB_ToplineBudget_Summary",Kind="View"]}[Data],
					Filtered = Table.SelectRows(Fact, each [PeriodEnd] >= Range_Start and [PeriodEnd] <= Range_End)
				in
				    Filtered

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

